version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expenses
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
